import type { Metadata } from "next";
import "@/font/iranSans.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "بیاین تولد هوراد جون",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen w-full animate-gradient-x bg-gradient-to-r from-purple-400 via-purple-600 to-purple-800 bg-[length:200%_200%] font-iransans">
        {children}
      </body>
    </html>
  );
}
