import type { Metadata } from "next";
import "@/font/iranSans.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "🎂 بیاین تولد ماهور ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="animate-gradient-x font-iransans h-screen w-full bg-gradient-to-r from-purple-400 via-purple-600 to-purple-800 bg-[length:200%_200%]">
        {children}
      </body>
    </html>
  );
}
